# Generated by Django 4.2.1 on 2023-05-16 22:15

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(1)])),
                ('contenido', models.TextField(max_length=4000)),
                ('imagenes', models.ImageField(upload_to=None)),
                ('etiqueta', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('autor', models.CharField(default='unsigned_user', editable=False, max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
