# Generated by Django 4.2.1 on 2023-05-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_fecha_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_mod',
            field=models.DateTimeField(null=True),
        ),
    ]
